receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
        - job_name: my-service-1
          scrape_interval: 10s
          static_configs:
            - targets: [my-service-1:8888]
        - job_name: my-service-2
          scrape_interval: 10s
          static_configs:
            - targets: [my-service-2a:8888, my-service-2b:8888]

processors:
  batch:

exporters:

  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp

  otlphttp/seq:
    endpoint: http://seq:80/ingest/otlp

  otlp/jaeger:
    endpoint: jaeger:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlphttp/prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/seq]